title: Shinkook(Livingston) Cha
description: Personal website
author: Shinkook(Livingston) Cha

remote_theme: mmistakes/jekyll-theme-basically-basic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: Mathematical Statistics
    url: /mathematical_statistics.md

    
